### ISSUE TITLE
Class 'Twig_Extension' not found

### ISSUE THREAD

**Issue by dmmarmol** [HelgeSverre/slim-twig-i18n-example#1]
I've just cloned your repo to test it and when i go to the main index.php the browser throw me this error:

`Class 'Twig_Extension' not found in My/Project/Root/vendor/slim/views/TwigExtension.php on line 38` 

Maybe it's me, but i've installed all the composer packages and even when i can see the folder `vendor/twig/extensions/` i keep stuck there.

**Comment by HelgeSverre** [comment]
Do you get any errors when trying to run composer install?

**Comment by dmmarmol** [comment]
No, composer have installed all the packages normally

**Comment by HelgeSverre** [comment]
Try to delete the vendor folder and composer install again.

**Comment by davidchchang** [comment]
Deleting the vendor folder and running `php composer.phar update` worked for me. Thanks!

**Comment by HelgeSverre** [comment]
I have removed the vendor folder from the git repo, should fix any further problems like this.
